function vmrk = importfile(filename, dataLines)
%IMPORTFILE Import data from a text file
%  NAP002T0 = IMPORTFILE(FILENAME) reads data from text file FILENAME
%  for the default selection.  Returns the data as a table.
%
%  NAP002T0 = IMPORTFILE(FILE, DATALINES) reads data for the specified
%  row interval(s) of text file FILENAME. Specify DATALINES as a
%  positive scalar integer or a N-by-2 array of positive scalar integers
%  for dis-contiguous row intervals.
%
%  Example:
%  NAP002T0 = importfile("../B2_Data/NAP_002/NAP_002_T0.vmrk", [14, Inf]);
%
%  See also READTABLE.
%
% Auto-generated by MATLAB on 17-Mar-2020 12:42:31

%% Input handling

% If dataLines is not specified, define defaults
if nargin < 2
    dataLines = [14, Inf];
end

%% Setup the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 6);

% Specify range and delimiter
opts.DataLines = dataLines;
opts.Delimiter = ",";

% Specify column names and types
opts.VariableNames = ["Mk2Comment", "ControlBoxisnotconnectedviaUSB", "VarName3", "VarName4", "VarName5", "VarName6"];
opts.VariableTypes = ["string", "string", "string", "string", "string", "string"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";
opts.ConsecutiveDelimitersRule = "join";

% Specify variable properties
opts = setvaropts(opts, ["Mk2Comment", "ControlBoxisnotconnectedviaUSB", "VarName5"]);
opts = setvaropts(opts, ["Mk2Comment", "ControlBoxisnotconnectedviaUSB", "VarName5"]);

% Import the data
vmrk = readtable(filename, opts);

end
